### ISSUE TITLE
error installing maia

### ISSUE THREAD

**Issue by SOLOSOFTMA** [dokos-io/maia#1]
hi dokos
i hope u doing well i get this error trying to install maia any help please

ImportError: Module import failed for Patient Record (maia.maia.doctype.patient_record.patient_record Error: No module named address_and_contact)

**Comment by chdecultot** [comment]
Hi @SOLOSOFTMA,

Thanks for your interest in this application.
Sorry, we developed this version on ERPNext v7 and have not updated this repo after the breaking changes of ERPNext v8.
Currently we use a forked version of Frappe and ERPNext, this is why we have not updated this repo further, as it would require a lot of work to make a clean, installable version of Maia on a vanilla ERPNext/Frappe stack. We would like to do in the near future though.

If you want to test Maia, you can still install ERPNext v7 and you will be able to install this app without issues.

Thanks for your understanding !
